### ISSUE TITLE
sosfiltfilt_dyn missing padding functionality

### ISSUE THREAD

**Issue by oyvindln** [qsib-cbie/sci-rs#60]
Hi and thanks for the work on this library so far

The sosfiltfilt_dyn function is missing the padding arguments and functionality of the upstream function. If you are meant to use the pad function in conjunction with it to replicate this it's not very clear how to do that.

**Comment by trueb2** [comment]
With the current implementation, you should be able to get the same results as scipy for the default configuration. `sosfiltfilt_dyn` has the default padding options implemented: https://github.com/qsib-cbie/sci-rs/blob/bdeaf1da03de4fffc7a7a879c6c956e548ca350e/sci-rs/src/signal/filter/sosfiltfilt.rs#L31 

I don't think we ran across a use case that needed the other options, but feel free to add it. It would require a breaking interface change to add an enum, but we could bump the minor version of the crate.

I think `ConvolveMode` provides an example similar to what would be required for all the padding options. https://github.com/qsib-cbie/sci-rs/blob/bdeaf1da03de4fffc7a7a879c6c956e548ca350e/sci-rs/src/signal/convolve.rs#L6-L29

As I am writing that, I am seeing some stale comments about the similar situation that function used to have
```
 /// - `mode`: Convolution mode (currently only Full is supported) 
```

We could start out with something like `pub enum Pad { Odd }` and add cases as we have support.

**Comment by oyvindln** [comment]
Ah - I totally missed that it was using padding by default. For whatever reason I thought it was equivalent to the scipy function with padding set to None since it did not have the padding argument and didn't look at the source code - my bad, sorry about that.

I don't think I have any need for other padding options either as of now so no rush from my side to implement anything else. Might be worth noting it in the documentation though.

**Comment by trueb2** [comment]
Good to hear. 

Closing the issue since this is the current situation on most of the interfaces.
